"""Modiify relations

Revision ID: 2093896866ae
Revises: 
Create Date: 2024-05-03 19:35:32.914505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2093896866ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('history_record',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('flashcard',
    sa.Column('flashcard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=150), nullable=False),
    sa.Column('choice1', sa.String(length=150), nullable=False),
    sa.Column('choice2', sa.String(length=150), nullable=False),
    sa.Column('choice3', sa.String(length=150), nullable=False),
    sa.Column('choice4', sa.String(length=150), nullable=False),
    sa.Column('right_answer', sa.String(length=50), nullable=False),
    sa.Column('saved_answer', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['history_record.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flashcard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    op.drop_table('history_record')
    op.drop_table('user')
    # ### end Alembic commands ###
